import { SERVICE_LANDING_DATA, ServiceLandingDetail } from '../data/serviceLandingData';
import type { ServiceBlock, ServiceItem, ServicePageBuilder } from '../types';

function uid(prefix: string) {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

export const BLOCK_LABELS: Record<string, string> = {
  hero: 'هیرو / بنر خدمت',
  pageHero: 'هیرو صفحه',
  heroHeader: 'هدر هیرو',
  highlights: 'هایلایت‌ها',
  symptoms: 'نشانه‌ها و مخاطبان',
  process: 'مراحل فرآیند',
  features: 'ویژگی‌ها و مزایا',
  doctors: 'تیم متخصصین',
  testimonials: 'نظرات مراجعین',
  faqs: 'سوالات متداول',
  latestFaqs: 'آخرین سوالات متداول',
  contactInfo: 'اطلاعات تماس',
  cta: 'فراخوان اقدام (CTA)',
  richText: 'ویرایشگر متن',
  htmlCode: 'کد HTML',
  otherServices: 'سایر خدمات (چیپ)',
  servicesGrid: 'شبکه خدمات',
  contactCards: 'کارت‌های تماس',
  contactForm: 'فرم',
  articlesGrid: 'فهرست مقالات',
  imageCarousel: 'کروسل تصویر',
  videoPlayer: 'پخش‌کننده ویدئو',
  container: 'کانتینر / ستون‌ها',
  icon: 'آیکون',
  iconList: 'لیست آیکون',
  button: 'دکمه',
  staffCarousel: 'کروسل پرسنل',
  googleMap: 'نقشه گوگل',
  tabGallery: 'تب گالری',
  divider: 'خط',
  spacer: 'فاصله',
  singleImage: 'تصویر تکی',
  imageGallery: 'گالری تصاویر',
  verticalImageGallery: 'گالری تصاویر عمودی',
  beforeAfter: 'قبل / بعد',
  audioPlayer: 'پخش‌کننده صدا',
};

export const BLOCK_ICONS: Record<string, string> = {
  hero: 'web_asset',
  pageHero: 'crop_landscape',
  heroHeader: 'view_quilt',
  highlights: 'grid_view',
  symptoms: 'psychology',
  process: 'timeline',
  features: 'stars',
  doctors: 'groups',
  testimonials: 'format_quote',
  faqs: 'help',
  latestFaqs: 'quiz',
  contactInfo: 'contact_phone',
  cta: 'campaign',
  richText: 'notes',
  htmlCode: 'code',
  otherServices: 'apps',
  servicesGrid: 'view_module',
  contactCards: 'contact_mail',
  contactForm: 'mail',
  articlesGrid: 'newspaper',
  imageCarousel: 'view_carousel',
  videoPlayer: 'smart_display',
  container: 'view_column',
  icon: 'interests',
  iconList: 'checklist',
  button: 'smart_button',
  staffCarousel: 'view_carousel',
  googleMap: 'map',
  tabGallery: 'tab',
  divider: 'horizontal_rule',
  spacer: 'space_bar',
  singleImage: 'image',
  imageGallery: 'photo_library',
  verticalImageGallery: 'view_column',
  beforeAfter: 'compare',
  audioPlayer: 'headphones',
};

/** Widget types that must NOT be nested inside container columns */
const NON_NESTABLE_WIDGET_TYPES: ServiceBlock['type'][] = ['container'];

/**
 * Widgets safe to nest inside container columns.
 * Derived automatically from every widget registered in BLOCK_LABELS,
 * so newly added widgets show up here without manual updates.
 */
export const NESTABLE_WIDGET_TYPES: ServiceBlock['type'][] = (
  Object.keys(BLOCK_LABELS) as ServiceBlock['type'][]
).filter((t) => !NON_NESTABLE_WIDGET_TYPES.includes(t));

export const WIDGET_GROUPS: Array<{
  id: string;
  label: string;
  types: ServiceBlock['type'][];
}> = [
  {
    id: 'layout',
    label: 'چیدمان',
    types: ['container', 'divider', 'spacer', 'heroHeader', 'pageHero', 'hero'],
  },
  {
    id: 'media',
    label: 'رسانه',
    types: [
      'imageCarousel',
      'singleImage',
      'imageGallery',
      'verticalImageGallery',
      'beforeAfter',
      'audioPlayer',
      'videoPlayer',
      'icon',
      'googleMap',
      'tabGallery',
    ],
  },
  {
    id: 'content',
    label: 'محتوا',
    types: ['richText', 'htmlCode', 'highlights', 'features', 'iconList', 'button', 'process', 'symptoms', 'cta'],
  },
  {
    id: 'clinic',
    label: 'کلینیک',
    types: [
      'doctors',
      'staffCarousel',
      'servicesGrid',
      'otherServices',
      'articlesGrid',
      'testimonials',
      'faqs',
      'latestFaqs',
      'contactInfo',
      'contactCards',
      'contactForm',
    ],
  },
];

export function landingToBlocks(landing: ServiceLandingDetail): ServicePageBuilder {
  const blocks: ServiceBlock[] = [
    {
      id: uid('hero'),
      type: 'hero',
      props: {
        title: landing.title,
        subtitle: landing.subtitle,
        badge: landing.badge,
        heroImage: landing.heroImage,
        duration: landing.duration,
        format: landing.format,
        satisfactionRate: landing.satisfactionRate,
        sessionFeeNote: landing.sessionFeeNote || '',
      },
    },
    {
      id: uid('highlights'),
      type: 'highlights',
      props: { items: landing.highlights },
    },
    {
      id: uid('symptoms'),
      type: 'symptoms',
      props: {
        title: landing.symptomsTitle,
        subtitle: landing.symptomsSubtitle,
        items: landing.symptoms,
        columnsMobile: 1,
        columnsTablet: 2,
        columnsDesktop: 3,
        titleSize: 'lg',
        titleFontFamily: 'inherit',
        itemTitleSize: 'md',
        itemTitleFontFamily: 'inherit',
      },
    },
    {
      id: uid('process'),
      type: 'process',
      props: {
        title: 'مراحل مشاوره و درمان در کلینیک ژینو',
        eyebrow: 'فرآیند دریافت خدمت',
        steps: landing.processSteps,
        columnsMobile: 1,
        columnsTablet: 2,
        columnsDesktop: 4,
        titleSize: 'lg',
        titleFontFamily: 'inherit',
        itemTitleSize: 'md',
        itemTitleFontFamily: 'inherit',
      },
    },
    {
      id: uid('features'),
      type: 'features',
      props: {
        title: landing.featuresTitle,
        items: landing.features,
        columnsMobile: 1,
        columnsTablet: 2,
        columnsDesktop: 4,
        titleSize: 'lg',
        titleFontFamily: 'inherit',
        itemTitleSize: 'sm',
        itemTitleFontFamily: 'inherit',
      },
    },
    {
      id: uid('doctors'),
      type: 'doctors',
      props: {
        title: 'روانشناسان و درمانگران این خدمت',
        subtitle: 'متخصصین دارای پروانه نظام روانشناسی',
        specialtiesFilter: landing.specialtiesFilter,
        maxCount: 6,
      },
    },
    ...(false && landing.testimonials?.length
      ? [
          {
            id: uid('testimonials'),
            type: 'testimonials' as const,
            props: {
              title: 'نظرات و تجربیات مراجعین این خدمت',
              subtitle: 'بازخورد واقعی مراجعین کلینیک روانشناسی ژینو',
              items: landing.testimonials,
              columnsMobile: 1,
              columnsTablet: 2,
              columnsDesktop: 2,
              titleSize: 'lg',
              titleFontFamily: 'inherit',
              itemTitleSize: 'sm',
              itemTitleFontFamily: 'inherit',
            },
          },
        ]
      : []),
    {
      id: uid('faqs'),
      type: 'faqs',
      props: {
        title: 'سوالات متداول درباره این خدمت',
        subtitle: 'پاسخ شفاف به ابهامات متداول شما',
        items: landing.faqs,
      },
    },
    {
      id: uid('other'),
      type: 'otherServices',
      props: {
        title: 'مشاهده سایر خدمات و دپارتمان‌های کلینیک ژینو',
      },
    },
    {
      id: uid('cta'),
      type: 'cta',
      props: {
        badge: 'گام اول به سوی سلامت و آرامش روانی',
        title: 'همین امروز نوبت مشاوره خود را رزرو کنید',
        subtitle:
          'فرآیند رزرو نوبت کمتر از ۲ دقیقه زمان می‌برد. امکان دریافت نوبت‌های حضوری در مطب یا مشاوره ویدیویی آنلاین موجود است.',
        phoneLabel: '',
        phoneHref: '',
      },
    },
  ];

  return { version: 1, blocks };
}

export function createDefaultPageBuilder(service: Pick<ServiceItem, 'id' | 'title' | 'description' | 'duration' | 'format'>): ServicePageBuilder {
  const landing = SERVICE_LANDING_DATA[service.id];
  if (landing) return landingToBlocks(landing);

  return {
    version: 1,
    blocks: [
      {
        id: uid('hero'),
        type: 'hero',
        props: {
          title: service.title,
          subtitle: service.description,
          badge: 'دپارتمان تخصصی ژینو',
          heroImage:
            'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=1000',
          duration: service.duration || '۴۵ تا ۶۰ دقیقه',
          format: service.format || 'حضوری و آنلاین',
          satisfactionRate: '۹۸٪ رضایت مراجعین',
          sessionFeeNote: '',
        },
      },
      {
        id: uid('cta'),
        type: 'cta',
        props: {
          badge: 'گام اول به سوی سلامت و آرامش روانی',
          title: 'همین امروز نوبت مشاوره خود را رزرو کنید',
          subtitle: 'فرآیند رزرو نوبت کمتر از ۲ دقیقه زمان می‌برد.',
          phoneLabel: '',
          phoneHref: '',
        },
      },
    ],
  };
}

export function getPageBuilderForService(service: ServiceItem): ServicePageBuilder {
  if (service.pageBuilder?.blocks?.length) {
    return service.pageBuilder;
  }
  return createDefaultPageBuilder(service);
}

export function enrichServicesWithPageBuilder(services: ServiceItem[]): ServiceItem[] {
  return services.map((s) => ({
    ...s,
    pageBuilder: getPageBuilderForService(s),
  }));
}

export function createEmptyBlock(type: ServiceBlock['type']): ServiceBlock {
  const defaults: Record<ServiceBlock['type'], Record<string, unknown>> = {
    hero: {
      title: 'عنوان خدمت',
      subtitle: 'توضیح کوتاه خدمت',
      badge: 'دپارتمان تخصصی',
      heroImage:
        'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=1000',
      duration: '۴۵ دقیقه',
      format: 'حضوری و آنلاین',
      satisfactionRate: '۹۸٪ رضایت',
      sessionFeeNote: '',
    },
    pageHero: {
      badge: 'برچسب صفحه',
      title: 'عنوان صفحه',
      subtitle: 'توضیح کوتاه صفحه',
      showBooking: true,
      primaryCtaLabel: 'رزرو نوبت',
      secondaryCtaLabel: '',
      secondaryCtaScreen: 'services',
      imageMode: 'side',
      heroImage: '',
      imageAlt: '',
      overlayOpacity: 45,
    },
    heroHeader: {
      badge: 'مرکز روان‌درمانی و مشاوره ژینو',
      statusText: 'پذیرش فعال',
      showStatus: true,
      title: 'پناهگاهی برای یافتن آرامش و تعادل روان',
      titleHighlight: 'آرامش و تعادل روان',
      subtitle:
        'با بهره‌گیری از متدها و پژوهش‌های علمی و رویکردهای روز دنیا مسیر درمان اختصاصی شما را طراحی می‌کنیم.',
      contentAlign: 'start',
      mediaSide: 'end',
      titleSize: 'lg',
      accentColor: 'primary',
      sectionPadding: 'md',
      mediaRadius: 32,
      widthMode: 'full',
      widthModeMobile: 'full',
      widthModeTablet: 'full',
      widthPercent: 100,
      widthPx: 1200,
      widthAlign: 'center',
      background: 'none',
      backgroundColor: '#ffffff',
      backgroundImage: '',
      backgroundOverlay: 35,
      patternStyle: 'diagonal',
      patternColor: '#b5106a',
      patternSize: 16,
      patternOpacity: 0.1,
      patternAnimate: true,
      patternSpeed: 28,
      borderRadius: 0,
      paddingX: 0,
      marginTop: 0,
      marginBottom: 0,
      marginX: 0,
      showCta: true,
      ctaLabel: 'راهنمای آنلاین انتخاب درمانگر',
      ctaIcon: 'psychology',
      ctaAction: 'guide',
      ctaLink: '',
      ctaVariant: 'outline',
      departmentsTitle: 'دپارتمان‌های فعال برای دریافت خدمت فوری:',
      showDepartments: true,
      departments: [
        { icon: 'person', label: 'مشاوره فردی بزرگسال' },
        { icon: 'toys', label: 'بازی درمانی کودک' },
        { icon: 'favorite', label: 'مشاوره ازدواج' },
        { icon: 'neurology', label: 'نوروفیدبک' },
      ],
      showCarousel: true,
      carouselAutoplay: true,
      carouselIntervalMs: 5000,
      showCarouselDots: true,
      showCarouselArrows: true,
      showRatingBadge: true,
      showFloatingBadge: true,
      slides: [
        {
          image:
            'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1200',
          badge: 'اتاق مشاوره',
          title: 'اتاق تخصصی مشاوره و روان‌درمانی',
          description: 'فضای آرام با نور طبیعی، مبلمان ارگونومیک و حریم خصوصی کامل',
          rating: '۴.۹ از ۵.۰',
          floatingBadge: 'نوبت‌دهی آنلاین ۲۴/۷',
          floatingIcon: 'calendar_month',
        },
        {
          image:
            'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=1200',
          badge: 'جلسه درمانی',
          title: 'فضای امن برای گفت‌وگو و درمان',
          description: 'طراحی‌شده برای جلسات فردی، زوج و خانواده با استانداردهای حرفه‌ای',
          rating: '۴.۸ از ۵.۰',
          floatingBadge: 'رزرو حضوری و آنلاین',
          floatingIcon: 'event_available',
        },
      ],
      showStats: true,
      statsAnimate: false,
      stats: [
        { icon: 'verified', value: '+۱۲,۰۰۰', label: 'جلسه موفق درمانی' },
        { icon: 'sentiment_satisfied', value: '۹۸.۴٪', label: 'رضایت مراجعین' },
        { icon: 'groups', value: '+۱۵', label: 'روانشناس و درمانگر ارشد' },
      ],
    },
    highlights: {
      items: [
        { icon: 'schedule', label: 'مدت جلسه', value: '۴۵ دقیقه' },
        { icon: 'videocam', label: 'روش', value: 'حضوری / آنلاین' },
      ],
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 4,
    },
    symptoms: {
      title: 'چه زمانی مراجعه ضرورت دارد؟',
      subtitle: 'اگر با این چالش‌ها روبه‌رو هستید...',
      items: [{ icon: 'psychology', title: 'عنوان', desc: 'توضیح کوتاه' }],
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 3,
      titleSize: 'lg',
      titleFontFamily: 'inherit',
      itemTitleSize: 'md',
      itemTitleFontFamily: 'inherit',
    },
    process: {
      title: 'مراحل دریافت خدمت',
      eyebrow: 'فرآیند',
      steps: [
        { number: '۰۱', title: 'گام اول', desc: 'توضیح' },
        { number: '۰۲', title: 'گام دوم', desc: 'توضیح' },
      ],
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 4,
      titleSize: 'lg',
      titleFontFamily: 'inherit',
      itemTitleSize: 'md',
      itemTitleFontFamily: 'inherit',
    },
    features: {
      title: 'چرا کلینیک ژینو؟',
      items: [{ icon: 'security', title: 'ویژگی', desc: 'توضیح' }],
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 4,
      titleSize: 'lg',
      titleFontFamily: 'inherit',
      itemTitleSize: 'sm',
      itemTitleFontFamily: 'inherit',
    },
    doctors: {
      title: 'تیم متخصصین این خدمت',
      subtitle: 'روانشناسان دارای پروانه',
      specialtiesFilter: [],
      maxCount: 3,
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 3,
    },
    staffCarousel: {
      badge: 'کادر درمانی و روانشناسان کلینیک ژینو',
      title: 'متخصصین برجسته ما',
      subtitle: 'همراهان مجرب و تخصصی شما در مسیر بهبودی و خودشناسی',
      viewAllLabel: 'مشاهده همه',
      showViewAll: true,
      showArrows: true,
      showDots: true,
      autoplay: false,
      intervalMs: 5000,
      specialtiesFilter: [],
      maxCount: 0,
      onlyActive: true,
      bookingLabel: 'رزرو نوبت',
      profileLabel: 'پروفایل درمانگر',
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 4,
    },
    testimonials: {
      title: 'نظرات مراجعین',
      subtitle: 'بازخورد واقعی',
      items: [{ name: 'مراجع', role: 'مراجع کلینیک', comment: 'تجربه خوب', rating: 5 }],
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 2,
      titleSize: 'lg',
      titleFontFamily: 'inherit',
      itemTitleSize: 'sm',
      itemTitleFontFamily: 'inherit',
    },
    faqs: {
      title: 'سوالات متداول',
      subtitle: 'پاسخ به ابهامات',
      items: [{ question: 'سوال؟', answer: 'پاسخ...' }],
    },
    latestFaqs: {
      badge: 'پاسخ‌های تخصصی',
      title: 'آخرین سوالات متداول',
      subtitle: 'پرسش‌های پرتکرار مراجعین که توسط تیم کلینیک پاسخ داده شده‌اند',
      maxCount: 6,
      categoryFilter: [],
      showCategory: true,
      showLikes: true,
      showViewAll: true,
      viewAllLabel: 'مشاهده همه سوالات',
      accentStyle: 'soft',
      openFirst: true,
    },
    contactInfo: {
      badge: 'ارتباط با ما',
      title: 'اطلاعات تماس',
      subtitle: 'از طریق تلفن، پیام‌رسان‌ها یا مراجعه حضوری با کلینیک در ارتباط باشید',
      layout: 'cards',
      showPhones: true,
      showSocials: true,
      showAddresses: true,
      showMap: true,
    },
    cta: {
      badge: 'اقدام کنید',
      title: 'رزرو نوبت',
      subtitle: 'کمتر از ۲ دقیقه',
      phoneLabel: '',
      phoneHref: '',
    },
    richText: {
      html: '<p>متن دلخواه خود را اینجا بنویسید.</p>',
    },
    htmlCode: {
      html: '<!-- کد HTML خود را اینجا قرار دهید -->\n<div style="padding:16px;text-align:center">نمونه محتوا</div>',
      padded: true,
      maxWidth: 'full',
    },
    otherServices: {
      title: 'سایر خدمات کلینیک',
    },
    servicesGrid: {
      title: 'خدمات کلینیک',
      subtitle: 'انتخاب خدمت مناسب',
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 3,
    },
    contactCards: {
      title: '',
      subtitle: '',
      iconFilled: true,
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 3,
      items: [
        {
          icon: 'location_on',
          title: 'آدرس حضوری',
          body: 'تهران، میدان ونک',
          note: 'دسترسی آسان',
          accent: 'primary',
          dir: 'rtl',
          link: '',
          linkLabel: '',
        },
        {
          icon: 'call',
          title: 'شماره‌های تلفن',
          body: '۰۲۱-۸۸۷۷۶۶۵۵\n۰۲۱-۸۸۷۷۴۴۳۳',
          note: 'شنبه تا پنجشنبه ۹ الی ۲۰',
          accent: 'secondary',
          dir: 'ltr',
          link: 'tel:02188776655',
          linkLabel: 'تماس بگیرید',
        },
        {
          icon: 'mail',
          title: 'ایمیل',
          body: 'info@zhinoclinic.ir',
          note: 'پاسخ‌گویی در ساعات اداری',
          accent: 'tertiary',
          dir: 'ltr',
          link: 'mailto:info@zhinoclinic.ir',
          linkLabel: 'ارسال ایمیل',
        },
      ],
    },
    contactForm: {
      title: '',
      subtitle: '',
      formId: 'form-contact',
    },
    articlesGrid: {
      title: 'مقالات',
      subtitle: '',
      categoryFilter: '',
      titleQuery: '',
      sortBy: 'newest',
      layout: 'grid',
      maxCount: 6,
      showPagination: false,
      showSearch: false,
      showCategories: false,
      showExcerpt: true,
      showCategoryBadge: true,
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 3,
    },
    imageCarousel: {
      autoplay: true,
      intervalMs: 4500,
      showDots: true,
      showArrows: true,
      aspect: 'video',
      slides: [
        {
          image:
            'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=1200',
          caption: 'اسلاید ۱',
        },
        {
          image:
            'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=1200',
          caption: 'اسلاید ۲',
        },
      ],
    },
    videoPlayer: {
      title: '',
      sourceType: 'upload',
      videoUrl: '',
      posterImage: '',
      autoplay: false,
      muted: true,
      controls: true,
      aspect: 'video',
    },
    container: {
      columnCount: 2,
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 2,
      gap: 'md',
      columnsDirection: 'row',
      padding: 'md',
      paddingX: 20,
      paddingY: 20,
      marginTop: 0,
      marginBottom: 0,
      borderRadius: 28,
      shadow: 'none',
      background: 'none',
      backgroundColor: '#f1f5f9',
      backgroundImage: '',
      backgroundOverlay: 40,
      widthMode: 'contained',
      maxWidth: 1400,
      columns: [
        {
          id: uid('col'),
          blocks: [],
          widthMode: 'auto',
          widthValue: 50,
          paddingX: 0,
          paddingY: 0,
          marginTop: 0,
          marginBottom: 0,
          marginX: 0,
          backgroundColor: '',
          borderRadius: 0,
          alignH: 'stretch',
          alignV: 'start',
        },
        {
          id: uid('col'),
          blocks: [],
          widthMode: 'auto',
          widthValue: 50,
          paddingX: 0,
          paddingY: 0,
          marginTop: 0,
          marginBottom: 0,
          marginX: 0,
          backgroundColor: '',
          borderRadius: 0,
          alignH: 'stretch',
          alignV: 'start',
        },
      ],
    },
    icon: {
      icon: 'psychology',
      label: '',
      size: 48,
      color: 'primary',
      align: 'center',
      filled: false,
      linkTarget: '',
    },
    iconList: {
      iconSize: 28,
      color: 'primary',
      filled: false,
      gap: 'md',
      items: [
        {
          icon: 'check_circle',
          text: 'بیش از ۱۰ سال سابقه درخشان در حوزه سلامت روان',
          link: '',
        },
        {
          icon: 'check_circle',
          text: 'تیم متخصص با مدارج علمی معتبر از دانشگاه‌های برتر',
          link: '',
        },
        {
          icon: 'check_circle',
          text: 'محیطی کاملاً امن، استاندارد و با رعایت رازداری مطلق',
          link: '',
        },
      ],
    },
    button: {
      label: 'رزرو نوبت',
      icon: 'calendar_month',
      showIcon: true,
      iconPosition: 'start',
      color: 'primary',
      variant: 'solid',
      size: 'md',
      align: 'center',
      fullWidth: false,
      action: 'booking',
      link: '',
    },
    googleMap: {
      mode: 'coords',
      lat: 35.7575,
      lng: 51.4100,
      address: 'تهران، خیابان ولیعصر، میدان ونک',
      zoom: 15,
      height: 360,
      borderRadius: 24,
      showMarker: true,
    },
    tabGallery: {
      badge: 'تجهیزات استاندارد جهانی',
      title: 'اتاق بازی ما؛ جایی برای تولد دوباره',
      subtitle: 'امکانات و فضاهای استاندارد طراحی شده طبق پروتکل‌های بین‌المللی روانشناسی کودک',
      tabHint: 'کلیک برای نمایش',
      items: [
        {
          id: uid('tg'),
          title: 'میز شن‌بازی تخصصی',
          description: 'میز شن تخصصی برای درمان غیرکلامی اضطراب و تروماهای خردسالی',
          thumbnail:
            'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&q=80&w=200',
          image:
            'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&q=80&w=1200',
        },
        {
          id: uid('tg'),
          title: 'گوشه هنر درمانی',
          description: 'فضای امن برای بیان احساسات از طریق رنگ، کلاژ و خلاقیت',
          thumbnail:
            'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=200',
          image:
            'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=1200',
        },
        {
          id: uid('tg'),
          title: 'کنج کتاب‌خوانی کودکان',
          description: 'گوشه‌ای آرام برای قصه‌گویی، تخیل و تقویت مهارت‌های زبانی',
          thumbnail:
            'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=200',
          image:
            'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=1200',
        },
        {
          id: uid('tg'),
          title: 'سیستم مشاهده غیرمستقیم',
          description: 'امکان مشاهده حرفه‌ای جلسات برای آموزش والدین و سوپرویژن درمانگران',
          thumbnail:
            'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=200',
          image:
            'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=1200',
        },
      ],
    },
    divider: {
      widthMode: 'full',
      widthPercent: 100,
      widthPx: 280,
      thickness: 2,
      lineStyle: 'solid',
      color: 'outline',
      customColor: '#94a3b8',
      align: 'center',
      orientation: 'horizontal',
      spacing: 'md',
      contentMode: 'none',
      text: 'عنوان بخش',
      icon: 'auto_awesome',
      iconFilled: false,
      iconSize: 18,
      contentPlacement: 'center',
      contentGap: 12,
      textSize: 'sm',
      textWeight: 'bold',
      textColor: 'muted',
      textCustomColor: '',
      labelSurface: 'auto',
      fadeEnds: false,
      endCap: 'none',
    },
    spacer: {
      linked: true,
      size: 'md',
      height: 32,
      sizeTop: 'md',
      sizeBottom: 'md',
      paddingTop: 32,
      paddingBottom: 32,
      responsive: false,
      heightMobile: 24,
      heightTablet: 32,
      heightDesktop: 40,
      showGuide: true,
    },
    singleImage: {
      image: '',
      alt: '',
      caption: '',
      subtitle: '',
      widthMode: 'full',
      widthPercent: 100,
      widthPx: 640,
      aspect: 'auto',
      objectFit: 'cover',
      borderRadius: 16,
      align: 'center',
      shadow: true,
      captionPosition: 'below',
      clickBehavior: 'lightbox',
      linkUrl: '',
      openInNewTab: true,
    },
    imageGallery: {
      title: '',
      subtitle: '',
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 3,
      gap: 'md',
      aspect: 'square',
      objectFit: 'cover',
      borderRadius: 16,
      captionPosition: 'below',
      clickBehavior: 'lightbox',
      items: [
        {
          image:
            'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800',
          alt: '',
          caption: 'فضای مشاوره',
          subtitle: '',
          linkUrl: '',
        },
        {
          image:
            'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=800',
          alt: '',
          caption: 'جلسه درمانی',
          subtitle: '',
          linkUrl: '',
        },
        {
          image:
            'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800',
          alt: '',
          caption: 'محیط آرام کلینیک',
          subtitle: '',
          linkUrl: '',
        },
      ],
    },
    verticalImageGallery: {
      title: '',
      subtitle: '',
      columnsMobile: 1,
      columnsTablet: 2,
      columnsDesktop: 2,
      gap: 'md',
      borderRadius: 20,
      shadow: true,
      columnAnimate: true,
      animateSpeed: 28,
      maxHeight: 560,
      clickBehavior: 'lightbox',
      items: [
        {
          image:
            'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&q=80&w=800',
          alt: '',
          caption: '',
        },
        {
          image:
            'https://images.unsplash.com/photo-1587654780291-39c9404d745b?auto=format&fit=crop&q=80&w=800',
          alt: '',
          caption: '',
        },
        {
          image:
            'https://images.unsplash.com/photo-1567057419565-4349c49d8a04?auto=format&fit=crop&q=80&w=800',
          alt: '',
          caption: '',
        },
        {
          image:
            'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&q=80&w=600&h=900',
          alt: '',
          caption: '',
        },
      ],
    },
    beforeAfter: {
      title: '',
      subtitle: '',
      beforeImage:
        'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1200',
      afterImage:
        'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
      beforeLabel: 'قبل',
      afterLabel: 'بعد',
      beforeAlt: '',
      afterAlt: '',
      caption: '',
      showLabels: true,
      initialPosition: 50,
      orientation: 'horizontal',
      widthMode: 'full',
      widthPercent: 100,
      widthPx: 800,
      aspect: 'video',
      objectFit: 'cover',
      borderRadius: 16,
      align: 'center',
      shadow: true,
    },
    audioPlayer: {
      mode: 'single',
      title: '',
      subtitle: '',
      audioUrl: '',
      trackTitle: 'عنوان قطعه',
      artist: '',
      coverImage: '',
      tracks: [
        {
          url: '',
          title: 'قطعه ۱',
          artist: '',
          coverImage: '',
        },
        {
          url: '',
          title: 'قطعه ۲',
          artist: '',
          coverImage: '',
        },
      ],
      autoplay: false,
      loop: false,
      showCover: true,
      showPlaylist: true,
      layout: 'card',
      borderRadius: 20,
    },
  };

  return { id: uid(type), type, props: defaults[type] };
}
